import { FiUsers, FiDownload } from "react-icons/fi";
import { RxDashboard } from "react-icons/rx";
import { RiNewspaperFill } from "react-icons/ri";
import {
  SiSimpleanalytics,
  SiBookstack,
  SiBlockchaindotcom,
  SiGoogleclassroom,
} from "react-icons/si";
import {
  AiFillDatabase,
  AiFillNotification,
  AiOutlineTable,
  AiOutlinePlus,
  AiOutlineHome,
} from "react-icons/ai";
import {
  MdOutlineAnalytics,
  MdOutlinePayment,
  MdFamilyRestroom,
  MdQuiz,
  MdOutlineSimCardDownload,
  MdEmail,
  MdPerson,
  MdPrivacyTip,
  MdTableRestaurant,
  MdAssessment,
  MdOutlineSettings,
} from "react-icons/md";
import {
  FaSchool,
  FaFileExcel,
  FaFileInvoice,
  FaChalkboardTeacher,
  FaShuttleVan,
  FaFileInvoiceDollar,
  FaDesktop,
  FaBookOpen,
  FaClipboardList,
  FaUsers,
  FaRoute,
  FaBox,
  FaMoneyBillAlt,
  FaHandsHelping,
  FaGraduationCap,
  FaCogs,
} from "react-icons/fa";
import { SlEvent } from "react-icons/sl";
import {
  BsBookFill,
  BsPaypal,
  BsFillChatLeftTextFill,
  BsFillClipboardXFill,
  BsDatabaseFillLock,
  BsBellFill,
} from "react-icons/bs";
import { GiRolledCloth, GiBookshelf } from "react-icons/gi";
import { TbReceiptTax, TbBuildingWarehouse } from "react-icons/tb";
import { ImBooks } from "react-icons/im";
import { BiTestTube, BiEdit } from "react-icons/bi";
import { HiOutlineLightBulb, HiOutlineIdentification } from "react-icons/hi2";

export default {
  Home: AiOutlineHome,
  Notification: BsBellFill,
  Plus: AiOutlinePlus,
  User: FiUsers,
  Credential: BsDatabaseFillLock,
  Dashboard: RxDashboard,
  Analytics: SiSimpleanalytics,
  Database: AiFillDatabase,
  Summary: MdOutlineAnalytics,
  Users: FiUsers,
  UsersGroup: FaUsers,
  PaymentCard: MdOutlinePayment,
  School: FaSchool,
  Calendar: SlEvent,
  NewsPaper: RiNewspaperFill,
  OpenBook: BsBookFill,
  Clothes: GiRolledCloth,
  Family: MdFamilyRestroom,
  Table: AiOutlineTable,
  Edit: BiEdit,
  Teachers: FaChalkboardTeacher,
  Announcement: AiFillNotification,
  Chat: BsFillChatLeftTextFill,
  Bus: FaShuttleVan,
  Tax: TbReceiptTax,
  Expenses: FaFileExcel,
  Result: FaFileExcel,
  Payroll: BsPaypal,
  Invoice: FaFileInvoice,
  Payment: FaFileInvoiceDollar,
  Book: ImBooks,
  Library: GiBookshelf,
  StackedBooks: SiBookstack,
  Board: BsFillClipboardXFill,
  Computer: FaDesktop,
  Quiz: MdQuiz,
  Exam: FaBookOpen,
  DownloadFile: MdOutlineSimCardDownload,
  Download: FiDownload,
  Email: MdEmail,
  List: FaClipboardList,
  Profile: MdPerson,
  Privilege: MdPrivacyTip,
  LogHistory: SiBlockchaindotcom,
  ClassRoom: SiGoogleclassroom,
  Route: FaRoute,
  Box: FaBox,
  Hostel: TbBuildingWarehouse,
  Dinning: MdTableRestaurant,
  Lab: BiTestTube,
  Customization: FaCogs,
  Billing: FaMoneyBillAlt,
  Support: FaHandsHelping,
  General: FaGraduationCap,
  Assessment: MdAssessment,
  Settings: MdOutlineSettings,
  Bulb: HiOutlineLightBulb,
  certificates: HiOutlineIdentification,
};
